/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as ClipClipIdRouteImport } from './routes/clip.$clipId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipClipIdRoute = ClipClipIdRouteImport.update({
  id: '/clip/$clipId',
  path: '/clip/$clipId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clips': typeof ClipsRoute
  '/processing': typeof ProcessingRoute
  '/clip/$clipId': typeof ClipClipIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clips': typeof ClipsRoute
  '/processing': typeof ProcessingRoute
  '/clip/$clipId': typeof ClipClipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clips': typeof ClipsRoute
  '/processing': typeof ProcessingRoute
  '/clip/$clipId': typeof ClipClipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clips' | '/processing' | '/clip/$clipId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clips' | '/processing' | '/clip/$clipId'
  id: '__root__' | '/' | '/clips' | '/processing' | '/clip/$clipId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClipsRoute: typeof ClipsRoute
  ProcessingRoute: typeof ProcessingRoute
  ClipClipIdRoute: typeof ClipClipIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clip/$clipId': {
      id: '/clip/$clipId'
      path: '/clip/$clipId'
      fullPath: '/clip/$clipId'
      preLoaderRoute: typeof ClipClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClipsRoute: ClipsRoute,
  ProcessingRoute: ProcessingRoute,
  ClipClipIdRoute: ClipClipIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
